import {
  AIAnalysisRequest,
  AIAnalysisResponse,
  AIThesisAnalysis,
  IAIProvider,
  MarketQuote,
} from '@/types';

/**
 * Sector benchmarks for Indian Equities (NSE/BSE)
 */
const SECTOR_BENCHMARKS: Record<
  string,
  { medianPE: number; medianPB: number; nature: 'asset_light' | 'capital_heavy' | 'financial' }
> = {
  'Information Technology': { medianPE: 26, medianPB: 6.5, nature: 'asset_light' },
  Financials: { medianPE: 16, medianPB: 2.2, nature: 'financial' },
  'Financial Services': { medianPE: 18, medianPB: 2.5, nature: 'financial' },
  'Consumer Goods': { medianPE: 42, medianPB: 8.0, nature: 'asset_light' },
  'Consumer Staples': { medianPE: 40, medianPB: 7.5, nature: 'asset_light' },
  Energy: { medianPE: 12, medianPB: 1.6, nature: 'capital_heavy' },
  'Oil & Gas': { medianPE: 11, medianPB: 1.5, nature: 'capital_heavy' },
  Healthcare: { medianPE: 28, medianPB: 4.0, nature: 'asset_light' },
  Automobile: { medianPE: 20, medianPB: 3.2, nature: 'capital_heavy' },
  Metals: { medianPE: 10, medianPB: 1.4, nature: 'capital_heavy' },
  Infrastructure: { medianPE: 17, medianPB: 2.0, nature: 'capital_heavy' },
};

/**
 * Financial Concept Knowledge Base for StockMentor AI
 */
const FINANCIAL_CONCEPTS: Record<string, { definition: string; practicalApplication: string; watchout: string }> = {
  'pe-ratio': {
    definition:
      'The Price-to-Earnings (P/E) ratio compares a company’s current share price to its per-share earnings (EPS). It indicates how many rupees investors are willing to pay for ₹1 of annual net profit.',
    practicalApplication:
      'Compare a company’s P/E against its own 5-year historical median and direct sector peers rather than across unrelated industries.',
    watchout:
      'A low P/E can be a "value trap" if company earnings are temporarily inflated by one-off asset sales or cyclical peaks.',
  },
  'pb-ratio': {
    definition:
      'The Price-to-Book (P/B) ratio compares the company’s market valuation against the accounting net asset value (book value) on its balance sheet.',
    practicalApplication:
      'Crucial for evaluating Indian public and private sector banks (PSU & Private Banks) and NBFCs, where loan assets represent the core earning engine.',
    watchout:
      'Less applicable for software and asset-light service firms where intellectual property and human capital do not reflect on the balance sheet.',
  },
  roce: {
    definition:
      'Return on Capital Employed (ROCE) measures how efficiently a company generates operating profit from total capital deployed (equity + debt).',
    practicalApplication:
      'Consistently earning an ROCE significantly higher than the borrowing cost (e.g., > 18% in India) signifies durable competitive advantage (economic moat).',
    watchout:
      'Ensure ROCE is not artificially inflated by aggressive asset depreciation or deferred maintenance.',
  },
  'free-cash-flow': {
    definition:
      'Free Cash Flow (FCF) is the actual cash generated by operating activities minus capital expenditures (CapEx) needed to maintain or expand physical assets.',
    practicalApplication:
      'Unlike accounting net profit, cash flow cannot be easily altered by accounting conventions. Sustainable dividends and buybacks come from FCF.',
    watchout:
      'A profitable company with persistent negative FCF may be struggling with delayed customer receivables or excessive inventory buildup.',
  },
  'debt-to-equity': {
    definition:
      'Debt-to-Equity (D/E) measures the proportion of borrowed capital relative to net shareholder equity.',
    practicalApplication:
      'A D/E ratio under 0.5 is considered conservative for manufacturing companies. Net-debt-free companies enjoy resilience during interest rate tightening.',
    watchout:
      'Does not apply cleanly to banks and finance firms, whose core operating model involves accepting debt/deposits to lend.',
  },
  'promoter-pledging': {
    definition:
      'Promoter pledging occurs when company founders and promoters collateralize their equity shares with lenders or NBFCs to secure loans.',
    practicalApplication:
      'High promoter pledging (> 20% of promoter stake) is a red flag. If share prices decline sharply, lenders may trigger margin calls and dump shares in the open market.',
    watchout:
      'Always check quarterly corporate governance filings on NSE/BSE to track changes in pledged share percentages.',
  },
};

export class GeminiProvider implements IAIProvider {
  public readonly providerName = 'StockMentor AI Financial Evidence Engine';

  /**
   * Educational concept explainer for Indian retail investors
   */
  async explainConcept(concept: string): Promise<string> {
    const key = concept.toLowerCase().trim().replace(/\s+/g, '-');
    const entry = FINANCIAL_CONCEPTS[key];

    if (entry) {
      return `### ${concept.toUpperCase()} — Educational Deep Dive\n\n**Definition:**\n${entry.definition}\n\n**How Savvy Investors Use It:**\n${entry.practicalApplication}\n\n**Critical Watch-out:**\n${entry.watchout}\n\n*Note: StockMentor AI explanations are strictly for educational research.*`;
    }

    // Dynamic reasoning if optional Gemini API key is configured
    const apiKey = process.env.GEMINI_API_KEY;
    if (apiKey) {
      try {
        const prompt = `You are StockMentor AI, an objective educational assistant for Indian retail investors. Explain the financial or market concept "${concept}" concisely in 3 sections: 1. Plain-English Definition, 2. Practical Application for NSE/BSE investors, 3. Critical Watch-out. Maintain a strictly objective tone with zero stock recommendations.`;
        const res = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ parts: [{ text: prompt }] }],
              generationConfig: { maxOutputTokens: 600, temperature: 0.3 },
            }),
          }
        );
        if (res.ok) {
          const json = await res.json();
          const text = json.candidates?.[0]?.content?.parts?.[0]?.text;
          if (text) return text;
        }
      } catch (err) {
        console.warn('Gemini API call failed, falling back to heuristic explanation:', err);
      }
    }

    return `### Understanding ${concept}\n\nIn equity research, ${concept} represents an analytical metric used by analysts to evaluate operating efficiency, liquidity, or capital allocation. When studying Indian listed companies on NSE or BSE, review the notes to accounts in the latest Annual Report (Form 20-F / Integrated Annual Report) to observe historical 3-year consistency.`;
  }

  /**
   * Evidence analyzer
   */
  async analyzeEvidence(request: AIAnalysisRequest): Promise<AIAnalysisResponse> {
    const summary = `StockMentor AI objective evidence synthesis on "${request.topic}".`;
    const educationalEvidence = [
      'Valuation metrics must always be benchmarked against the historical cycle of the specific industry.',
      'Check cash conversion cycles (DSO) to ensure sales translate into realized bank deposits.',
      'Evaluate promoter holding trends: steady or increasing promoter ownership historically reflects alignment with minority shareholders.',
    ];

    return {
      summary,
      educationalEvidence,
      disclaimer:
        'StockMentor AI provides educational evidence synthesis. We do not provide investment advice, buy/sell ratings, or return forecasts.',
    };
  }

  /**
   * Balance sheet and valuation thesis analyzer for a specific Indian stock
   */
  async analyzeStockThesis(quote: MarketQuote): Promise<AIThesisAnalysis> {
    const symbol = quote.symbol;
    const cleanSym = symbol.replace('.NS', '').replace('.BO', '');
    const companyName = quote.name || cleanSym;
    const pe = quote.peRatio;
    const pb = quote.pbRatio;
    const sector = quote.sector || 'General Market';
    const benchmark = SECTOR_BENCHMARKS[sector] || { medianPE: 22, medianPB: 3.0, nature: 'asset_light' };

    // 1. Valuation Assessment
    let valuationAssessment: 'fair' | 'growth_premium' | 'undervalued' | 'speculative' = 'fair';
    let valuationEvidence = '';

    if (pe !== undefined && pe > 0) {
      if (pe > 75) {
        valuationAssessment = 'speculative';
        valuationEvidence = `${companyName} trades at a P/E multiple of ${pe.toFixed(1)}x, well above traditional equity thresholds. The market is pricing in aggressive multi-year earnings compounding. Retail investors must verify whether revenue growth and operating margins can sustain this premium.`;
      } else if (pe > benchmark.medianPE * 1.35) {
        valuationAssessment = 'growth_premium';
        valuationEvidence = `At ${pe.toFixed(1)}x P/E, ${cleanSym} trades at a premium to the ${sector} sector baseline (median ~${benchmark.medianPE}x). This indicates elevated market expectations regarding its competitive moat, return on capital, or market share gains.`;
      } else if (pe < benchmark.medianPE * 0.75) {
        valuationAssessment = 'undervalued';
        valuationEvidence = `Trading at a P/E of ${pe.toFixed(1)}x compared to sector median of ~${benchmark.medianPE}x. While potentially offering a margin of safety, investors should investigate whether the discount stems from temporary cyclical headwind or structural margin degradation.`;
      } else {
        valuationAssessment = 'fair';
        valuationEvidence = `Current P/E of ${pe.toFixed(1)}x aligns reasonably with typical ${sector} sector valuations (~${benchmark.medianPE}x). Historical valuation stability suggests the market views future cash flows as moderately predictable.`;
      }
    } else if (pb !== undefined && pb > 0) {
      valuationAssessment = pb > benchmark.medianPB * 1.5 ? 'growth_premium' : 'fair';
      valuationEvidence = `Evaluating on Price-to-Book basis: ${companyName} trades at ${pb.toFixed(2)}x book value (Sector reference ~${benchmark.medianPB}x).`;
    } else {
      valuationAssessment = 'fair';
      valuationEvidence = `Sufficient trailing earnings metrics were not published in public feeds. Detailed valuation should be derived directly from latest audited quarterly financials filed with NSE/BSE.`;
    }

    // 2. Solvency & Balance Sheet Durability
    let solvencyStatus: 'conservative' | 'moderate' | 'capital_heavy' = 'moderate';
    let solvencyEvidence = '';

    if (benchmark.nature === 'financial') {
      solvencyStatus = 'moderate';
      solvencyEvidence = `As a financial/banking entity, capital adequacy ratio (CAR / CRAR) and provisioning coverage (PCR) are the paramount solvency indicators rather than conventional debt-to-equity.`;
    } else if (benchmark.nature === 'capital_heavy') {
      solvencyStatus = 'capital_heavy';
      solvencyEvidence = `Operating in a capital-intensive sector (${sector}). Watch interest coverage ratio (EBIT / Interest Expense) to ensure fixed financial costs remain well-protected during cyclical downturns.`;
    } else {
      solvencyStatus = 'conservative';
      solvencyEvidence = `Asset-light operating profile typically characterized by low working-capital requirements and conservative debt levels. Surplus cash generation supports continuous R&D and shareholder returns.`;
    }

    // 3. Sector-Specific Self-Guided Thesis Questions
    const thesisQuestions: string[] = [];
    if (sector.includes('IT') || sector.includes('Technology')) {
      thesisQuestions.push(
        'Are large deal total contract values (TCV) growing quarter-over-quarter?',
        'How effectively is management offsetting wage inflation with automation and offshore delivery?',
        'Does the company have direct exposure to discretionary banking/retail tech spend in the US and Europe?',
        'Is Free Cash Flow conversion maintaining a ratio of >85% against reported Net Profit?'
      );
    } else if (sector.includes('Financial') || sector.includes('Bank')) {
      thesisQuestions.push(
        'What is the direction of Net Interest Margins (NIM) in the current interest rate regime?',
        'Are Gross and Net Non-Performing Assets (NPAs) showing a consistent declining or stable trajectory?',
        'What proportion of total deposits consists of low-cost CASA (Current & Savings Accounts)?',
        'Is the Capital Adequacy Ratio (CAR) well above the RBI statutory requirement (11.5%)?'
      );
    } else if (sector.includes('Consumer') || sector.includes('FMCG')) {
      thesisQuestions.push(
        'Can the company pass on raw material input cost inflation through pricing without hurting sales volume?',
        'What percentage of revenue is driven by new product innovations launched in the last 3 years?',
        'How deep and direct is the rural and semi-urban distribution reach compared to regional competitors?',
        'Is advertising and promotional spending yielding measurable market share retention?'
      );
    } else {
      thesisQuestions.push(
        'Does the business possess pricing power that protects margins against raw material inflation?',
        'Is the current Return on Capital Employed (ROCE) comfortably above the cost of capital (>15%)?',
        'Are operating cash flows consistently positive and sufficient to fund future CapEx without fresh debt?',
        'Has promoter holding remained stable without any pledging of shares to NBFCs or banks?'
      );
    }

    // 4. Sector Key Risks
    const keyRisks: string[] = [];
    if (sector.includes('IT')) {
      keyRisks.push(
        'Currency volatility between USD/EUR and INR impacting operating margins.',
        'Slowdown in discretionary enterprise software spending across North America and Europe.',
        'Attrition rates and talent cost inflation in high-skill technology domains.'
      );
    } else if (sector.includes('Financial')) {
      keyRisks.push(
        'Unanticipated slippages in unsecured retail or microfinance loan books.',
        'Deposit rate competition compressing Net Interest Margins (NIM).',
        'Regulatory changes by the Reserve Bank of India regarding risk-weights and provisioning.'
      );
    } else if (sector.includes('Consumer')) {
      keyRisks.push(
        'Commodity price volatility in agricultural inputs, packaging, and crude oil derivatives.',
        'Intense competition from agile direct-to-consumer (D2C) brands eroding market share.',
        'Rural demand softness linked to uneven monsoon rainfall patterns across India.'
      );
    } else {
      keyRisks.push(
        'Cyclical downturns in industrial demand reducing capacity utilization rates.',
        'Rising domestic or global interest rates increasing borrowing and debt refinancing costs.',
        'Regulatory or tariff modifications impacting import-export economics.'
      );
    }

    const businessSummary =
      quote.summary ||
      `${companyName} is an Indian enterprise listed on ${quote.exchange} representing the ${sector} sector.`;

    const disclaimer =
      'StockMentor AI provides educational balance sheet analysis and objective evidence synthesis. This is not investment advice, SEBI research analysis, or a recommendation to buy, hold, or sell any security.';

    return {
      symbol,
      companyName,
      businessSummary,
      valuationAssessment,
      valuationEvidence,
      solvencyStatus,
      solvencyEvidence,
      thesisQuestions,
      keyRisks,
      disclaimer,
    };
  }
}
